### ISSUE TITLE
logging into the same account twice produces a bad result

### ISSUE THREAD

**Issue by seiyria** [LandOfTheRair/core2#10]
on the first instance, it will log in normally.

when the second instance logs in, it will:

- not send that information to the first instance (expected)
- show the same user in the second instance list twice (not expected)

**Comment by Oipo** [comment]
Is this still an issue after the porting to the new websocket library? Can you re-test?

**Comment by seiyria** [comment]
as far as I can tell, this is still an issue 

![](https://i.imgur.com/9UT3wsd.png)

**Comment by Oipo** [comment]
Oh, I assumed that the frontend inserts the logged in player into the online users entries. If that's an incorrect assumption, let me know.

**Comment by seiyria** [comment]
The list is only updated when:

- a user logs in (Auth:join)
- the current user list is synced (Auth:login_response)

So the first instance gets a join, but the user that's logged in is itself so it gets added anyway. The second instance just gets a login response, which does not appear to include itself as a previously logged in user. So, probably, Auth:join shouldn't fire if the current user is already logged in.

**Comment by Oipo** [comment]
I couldn't reproduce Auth:join firing when second user logs in. Instead, I suspect it is because the second user gets a list of online_users with the first user included. That's what the commit removes: online_users never get filled with the user itself, only other users.

**Comment by seiyria** [comment]
https://i.imgur.com/fwefYnN.png

Now, no users are in the list on join.

**Comment by Oipo** [comment]
As mentioned, the online_users array does not include the logging in user. Please be so kind as to insert that user into the array client-side, as server-side logic for that would be more complicated than doing it client-side.
