### ISSUE TITLE
Put allegiances and classes in yml files, add API command to retrieve all possibilities

### ISSUE THREAD

**Issue by seiyria** [LandOfTheRair/core2#5]
just rename it to .yml

[charselect.txt](https://github.com/LandOfTheRair/core2/files/3639922/charselect.txt)

**Comment by seiyria** [comment]
The YML should probably also go in the Content repo for consistency.

**Comment by Oipo** [comment]
Fixed in 5226129456d0c56de6e36058c9edc80e6e7d05eb
